//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotMatrix.Core.Cryptopia.WalletService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cryptopia.WalletService.IWalletService")]
    public interface IWalletService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWalletService/GenerateAddress", ReplyAction="http://tempuri.org/IWalletService/GenerateAddressResponse")]
        string GenerateAddress(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWalletService/GenerateAddress", ReplyAction="http://tempuri.org/IWalletService/GenerateAddressResponse")]
        System.Threading.Tasks.Task<string> GenerateAddressAsync(string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWalletServiceChannel : DotMatrix.Core.Cryptopia.WalletService.IWalletService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WalletServiceClient : System.ServiceModel.ClientBase<DotMatrix.Core.Cryptopia.WalletService.IWalletService>, DotMatrix.Core.Cryptopia.WalletService.IWalletService {
        
        public WalletServiceClient() {
        }
        
        public WalletServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WalletServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WalletServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WalletServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateAddress(string userId) {
            return base.Channel.GenerateAddress(userId);
        }
        
        public System.Threading.Tasks.Task<string> GenerateAddressAsync(string userId) {
            return base.Channel.GenerateAddressAsync(userId);
        }
    }
}
